---
title: "Between-Strain Analysis"
params:
    comb: c("Tau", "C57")
    age: "old"
    sex: "F"
editor: visual
toc: true
---

```{r}
#| label: setup
#| include: FALSE

# Import utility functions
source("globals.R")

# Set chunks options
knitr::opts_chunk$set(
  warning = FALSE, message = FALSE, echo = FALSE,
  fig.path = paste0("plots/", paste(params$comb, collapse = "_")),
  dev = c("png", "pdf")
)
```

## Overview

```{r}
#| label: data
figure <- readPNG("data/opac_meninges.png")
df <- read.csv("data/processed_data.csv")

df <- df %>%
  filter(Strain %in% params$comb, Y < outlier_threshold,
         Age == params$age, Sex %in% params$sex) %>%
  mutate(Phenotype = as.factor(Phenotype),
         Sex.Strain = as.factor(Sex.Strain))
```

In this report we compare the distribution of Tertiary Lymphatic Structures
(TLSs) in the meninges of mice from two different strains:
`r paste(params$comb, collapse = " and ")`. Only
`r paste(unique(df$SexText), collapse = " and ")` at a `r params$age` age were
taken into consideration.

```{r}
#| label: plot-size
upper_lim <- max(meninges_height, max(df$Y[df$Y < outlier_threshold]))
side_lim <- max(meninges_width, max(abs(df$X)))
lower_lim <- min(-meninges_bottom, min(df$Y))
```

## Exploratory statistics

```{r}
#| label: tbl-stats
#| tbl-cap: Basic statistics on the TLSs from mice meninges. Size and length are measured in mm, whereas phenotype and sinus location are reported in terms of the number of structures per each phenotype or sinus location, respectively.
df %>%
  group_by(Sex, Strain) %>%
  summarise(Mice = n_distinct(TissueID),
            Structures = n(),
            AvgDiameter = round(mean(Size), 1),
            AvgDistance = round(mean(Length), 1),
            `Phenotype (1-2-3)` = paste(sum(Phenotype == 1), sum(Phenotype == 2), sum(Phenotype == 3), sep = "-"),
            `Sinus (0-90-180)` = paste(sum(Sinus == 0), sum(Sinus == 90), sum(Sinus == 180), sep = "-"),
            Desc = unique(AgeText)) %>%
  knitr::kable()
```


## Comparison of Distributions

```{r}
#| label: text-inset
text_df <- df %>%
  group_by(SexText, Strain) %>%
  summarise(Mice = n_distinct(TissueID),
            Count = n()) %>%
  mutate(Label = paste(Count, "TLS from", Mice, "subjects"))

insets <- df %>%
  split(f = .$Sex.Strain, drop = TRUE) %>%
  purrr::map(~annotation_custom2(
    data = ., grob = ggplotGrob(get_inset(., my_cols)),
    xmin = -side_lim - 1, xmax = -side_lim + 3.5,
    ymin = upper_lim - 4.5, ymax = upper_lim)
  )
```

```{r}
#| label: fig-loc
#| fig-cap: Scatter plot of TLSs around meninges. Each dot represents one structure, sized by dimension, coloured by phenotype and labeled by sample. Each panel corresponds to a mice group based on sex and age category.
#| fig-width: !expr 5 + 2.75 * (n_distinct(df$Strain) - 1)
#| fig-height: !expr 1 + 3.5 * n_distinct(df$Sex)
ggplot(df, aes(x = X, y = Y)) +
  lims(x = c(-side_lim, side_lim), y = c(lower_lim, upper_lim)) +
  insets +
  annotation_custom(rasterGrob(figure, 
                               width = unit(1, "npc"), 
                               height = unit(1, "npc")), 
                    -meninges_width, meninges_width,
                    -meninges_bottom, meninges_height) +
  geom_point(alpha = my_alpha, aes(colour = Phenotype, size = Size)) +
  geom_text(data = text_df, aes(label = Label),
            x = -side_lim + 2.4, y = upper_lim + 0.3, size = 3) +
  scale_colour_manual(values = my_cols) +
  scale_size_continuous(limits = size_lims, breaks = size_breaks) +
  labs(x = "X in mm", y = "Y in mm") +
  facet_grid(SexText ~ Strain) +
  theme_classic()
```

```{r}
#| label: fig-loc-dens
#| fig-cap: Density plot of TLSs around meninges. Each dot represents one structure, sized by dimension, coloured by phenotype. Colour indicates the fraction of structures found in each pixel. Each panel corresponds to a mice group based on sex and age category.
#| fig-width: !expr 5 + 2.75 * (n_distinct(df$Strain) - 1)
#| fig-height: !expr 1 + 3.5 * n_distinct(df$Sex)
ggplot(df, aes(x = X, y = Y)) +
  lims(x = c(-side_lim, side_lim), y = c(lower_lim, upper_lim)) +
  geom_hex(bins = bin_num) +
  insets +
  annotation_custom(rasterGrob(figure, 
                               width = unit(1, "npc"), 
                               height = unit(1, "npc")), 
                    -meninges_width, meninges_width,
                    -meninges_bottom, meninges_height) +
  geom_point(aes(colour = Phenotype, size = Size), alpha = my_alpha) +
  geom_text(data = text_df, aes(label = Label),
            x = -side_lim + 2.4, y = upper_lim + 0.3, size = 3) +
  scale_colour_manual(values = my_cols) +
  scale_size_continuous(limits = size_lims, breaks = size_breaks) +
  scale_fill_gradient2(low = col_low, high = col_high, limits = col_lims) +
  labs(x = "X in mm", y = "Y in mm", fill = "Count") +
  facet_grid(SexText ~ Strain) +
  theme_classic()
```

